### ISSUE TITLE
Failure on merb require

### ISSUE THREAD

**Issue by CodeMonkeySteve** [mtodd/halcyon#1]
With halcyon 0.5.4 and merb-core 1.0.15:

```
$ halcyon
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- merb-core/vendor/facets (LoadError)
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/lib/ruby/gems/1.8/gems/halcyon-0.5.4/bin/../lib/halcyon.rb:3                                                                  
        from /usr/lib/ruby/gems/1.8/gems/halcyon-0.5.4/bin/../lib/halcyon.rb:3:in `each'                                                        
        from /usr/lib/ruby/gems/1.8/gems/halcyon-0.5.4/bin/../lib/halcyon.rb:3                                                                  
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'                                                
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'                                                             
        from /usr/lib/ruby/gems/1.8/gems/halcyon-0.5.4/bin/halcyon:3                                                                            
        from /usr/bin/halcyon:19:in `load'                                                                                                      
        from /usr/bin/halcyon:19                                                                                                                
```

**Comment by mtodd** [comment]
This is a known issue. Halcyon is not compatible with any version of Merb 0.9 or higher. There was some work done to patch Merb to get it to a workable point, but development on Halcyon has completely stopped. This was a matter of choice.

Unless you're personally willing to take over maintenance and development, this issue is considered Won't Fix. Sorry :(

**Comment by mtodd** [comment]
Accidentally closed; will leave open so that others can see this message and fix it if they feel so inclined.

Just to clarify, Halcyon does not have an active maintainer currently, and the old one (me) doesn't mind if someone wants to step up and take over. I'm all for it.

**Comment by ghost** [comment]
Hello, seems I'm very late for the party,
as a beginner in ruby world had the exact same error. This framework seemed to be exactly what I needed to build stuff with no UI and that works in background. Is there any alternatives to it ?
